# Generated by Django 5.0.4 on 2024-04-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('descricao', models.TextField(max_length=255)),
                ('qtd_entrada', models.IntegerField()),
                ('qtd_atual', models.IntegerField()),
                ('data_fabricacao', models.DateField()),
                ('data_validade', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tarefa',
        ),
    ]
