# Generated by Django 5.0.4 on 2024-04-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validade', '0002_produto_delete_tarefa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.IntegerField(verbose_name='Código'),
        ),
    ]
