# Generated by Django 5.0.4 on 2024-04-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validade', '0003_alter_produto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_fabricacao',
            field=models.DateField(verbose_name='Data Fabricação'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_validade',
            field=models.DateField(verbose_name='Data Validade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='qtd_atual',
            field=models.IntegerField(verbose_name='Quantidade Atual'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='qtd_entrada',
            field=models.IntegerField(verbose_name='Quantidade Entrada'),
        ),
    ]
