# Generated by Django 5.0.4 on 2024-04-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validade', '0004_alter_produto_data_fabricacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
    ]
